### ISSUE TITLE
微信账号与主站绑定是如何实现

### ISSUE THREAD

**Issue by riddle911** [ToadWoo/bookbox-wxapp#2]
老哥 我看你的程序里有绑定主站账号的功能，想问下具体实现是个什么思路，
还是得借助微信认证后的那个openid以及oauth之类的那一套吗

**Comment by ToadWoo** [comment]
这个绑定是在他输入账号密码后去登录主站，然后记住他的token，下次请求其他接口数据只要根据这个token去请求就可以了。如果他没有这个token就说明没有绑定，如果token过期了需要再拿账号密码跟新下token

**Comment by riddle911** [comment]
噢- -明白了 那就是说你这个不是一般做的那种sso 就相当于是做了一个页面内记住密码的操作吧？

**Comment by ToadWoo** [comment]
是的 学校系统应该都有有做第三方授权登录绑定的功能 只能这么模拟绑定吧
